# Numpy array

In [2]:
import numpy as np

np.array(['Saurabh', 2,5.3])

array(['Saurabh', '2', '5.3'], dtype='<U7')

In [3]:
np.array([1,2,3.0])

#Upcasting : All the numbers are converted into float values as it requires more memory

array([1., 2., 3.])

In [4]:
#Two dimensional array:

np.array([[1,2], [4,5]])

array([[1, 2],
       [4, 5]])

In [8]:
#Converting a normal array in any dimebsion you want:

np.array([10,20,30], ndmin = 6)  #Converted to 6 dimensions

array([[[[[[10, 20, 30]]]]]])

In [10]:
#Converting normal array values into conplex integers

np.array([10,20,30], dtype = complex)

array([10.+0.j, 20.+0.j, 30.+0.j])

In [20]:
x = np.array([(1,2), (3,4)], dtype = [('a', '<i2'), ('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [25]:
type(x[1][0])

numpy.int16

In [29]:
#Creating a Matrix from array

np.mat(np.array([[10,20], [30,40]])) #Just use np.mat funcation on top of no.array function

matrix([[10, 20],
        [30, 40]])

# Numpy asarray

In [33]:
#Converting a simple list into arrray

a = [10,20,30,40,50]
type(a)

list

In [37]:
type(np.asarray(a)) #Use can also use np.array function

numpy.ndarray

In [41]:
#Gerneral use of asarray function

np.asarray((1,2,4,5,6))

array([1, 2, 4, 5, 6])

In [48]:
#Setting data type of valuess inside array

a = np.array([1,2,3], dtype = np.float32)
a

array([1., 2., 3.], dtype=float32)

In [52]:
np.asarray([1,2]) is a

#This will retrun false because 'a' is having data type as floating integer

False

In [54]:
issubclass(np.matrix, np.ndarray)

True

# Numpy asanyarray

In [63]:
#Gerneral use by converting a list into array:

a = [1,2,3]
np.asanyarray(a)

array([1, 2, 3])

In [65]:
np.asanyarray([1,2])

array([1, 2])

In [79]:
#Use of copy function in Numpy

x = np.array([10,20,30])
x

array([10, 20, 30])

In [80]:
y = x  #This is NOT a copy because we are just refering x to y. the new variable y is occupying same location as of x
y

array([10, 20, 30])

In [92]:
#Any change in y will also change the x because both are referring to SAME location 

y[0] = 100
x 

#As seen below, 0th index to x is also changed to 100

[10, 20, 30]

In [90]:
#By creating a np.copy you cany copy the values of an array to DIFFERENT memory location
x = [10,20,30]

z = np.copy(x)

In [93]:
#Any changes in z will not change x because both are referring to DIFFERENT loccation
z[0] = 100
x

#As seen below, 0th index to x is NOT changed to 100

[10, 20, 30]

In [99]:
id(x[1])

140714590311840

# Numpy fromfunction

In [101]:
np.fromfunction(lambda i,j: i==j, (3,3))

#This will create 3x3 matrix and compare each row index with the corresponding column index and will give back boolean values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [102]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [105]:
#Creating record array from list of arrays

x1 = np.array([1,2,3,4])
x2 = np.array(['sau', 'tej', 'AAA', 'bbb'])
x3 = np.array([1.1, 2.2, 3.3, 4.4])
x4 = np.array([100,200,300,400])

In [107]:
np.core.records.fromarrays([x1,x2,x3,x4])

#This will grab all the elements index wise from all the arrays

rec.array([(1, 'sau', 1.1, 100), (2, 'tej', 2.2, 200),
           (3, 'AAA', 3.3, 300), (4, 'bbb', 4.4, 400)],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<i4')])

In [110]:
#Creating sample data

my_mat = [[10,20,30],[40,50,60],[70,80,90]]
mat = np.array(my_mat)

In [116]:
mat.ndim #ndim gives the dimensison, 2 for a matrix, 1 for a vector

2

In [117]:
mat.size #gives the total number of elements

9

In [118]:
mat.shape #gives the number of elements along each axes (dimension)

(3, 3)

In [119]:
mat.dtype #gives the data type contained in the array

dtype('int32')

# Numpy arange & linspace

In [130]:
#Using simple arange fuction

np.arange(0,10,2) #tp get the array of number starting with 0 and NOT including 10 with step (jump) of 2

array([0, 2, 4, 6, 8])

In [140]:
np.arange(0,15,2.5) # Numbers spaced apart by 2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5])

In [142]:
np.linspace (1,7,25) 

#This will give array of number starting with 1 and ending with 7 equally divided in 25 parts
#You will get 25 number of values starting with and ending with 7|

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  ])

# Nimpy creation of Matrix

In [150]:
np.zeros(3) #No. of columns with single row

array([0., 0., 0.])

In [151]:
np.zeros((2,4)) #2:Row and 4:column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
np.zeros((2,4,3)) #2:No.of matrices 4: Row and 3:Columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [152]:
np.ones(3) #No. of columns with single row

array([1., 1., 1.])

In [154]:
np.ones((2,4)) #2:Row and 4:column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [158]:
np.ones((2,4,3)) #2:No.of matrices 4: Row and 3:Columns

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [160]:
# Mathematical operations with matrix

5+np.ones((2,4,3))

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [168]:
#Creation of Idetity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [171]:
np.logspace(2,3, num=4, base=10)

#It will display 4 log results of equally distributed numbers between 2 and 3

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [176]:
w = np.arange(25).reshape(5,5)
w

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [178]:
np.diag(w) #To get the diagonal elements from the matrix

array([ 0,  6, 12, 18, 24])

In [180]:
np.diag(w, k=2)  #this will strike out first 2 two columns and last 2 rows and then will print diagonal of resultant matrix

array([ 2,  8, 14])

In [184]:
np.diag(w, k=-2) #this will strike out last 2 two columns and first 2 rows and then will print diagonal of resultant matrix

array([10, 16, 22])

# Numpy Random Function

In [186]:
np.random.rand(3,4)

#This will create 3x4 matrix of numbers between 0 and 1 which are equally distributed

array([[0.93450726, 0.27855283, 0.89553899, 0.06062182],
       [0.27406492, 0.71463491, 0.33941862, 0.70608894],
       [0.03676427, 0.84702018, 0.88298296, 0.27302691]])

In [188]:
np.random.randn(3,4)

#This will create 3x4 matrix of numbers which are Normally Distributed (i.e. Mean = 0 and Std. Deviation = 0)

array([[-0.2214318 ,  0.83501505,  0.04099764,  0.80235605],
       [ 0.79294554,  0.53235839, -0.64093694,  1.74370501],
       [ 0.58268161,  0.98536545, -0.26559573, -0.37435305]])

In [196]:
np.random.randint(1,10)

#This will create any one random integer between 1 and 10 

8

In [198]:
np.random.randint (1,100, (3,3))

#random integers between 1 and 100 and arranged in 3x3 matrix

array([[94, 61, 40],
       [ 2, 25, 84],
       [71, 86, 67]])

In [199]:
#20 Sample of dice thrown

np.random.randint(1,7, 20)

array([5, 6, 1, 4, 3, 2, 5, 6, 2, 2, 5, 2, 2, 3, 4, 3, 4, 3, 5, 2])

# Numpy Indexing and Slicing

In [207]:
arr = np.arange(0,100,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [208]:
arr[6]

60

In [211]:
arr[4:8] #Fetching from 4th index till 7th index

array([40, 50, 60, 70])

In [216]:
arr[4:8:2] #Fetching from 4th index till 7th index with step (jump) size of 2

array([40, 60])

In [221]:
#Creating data
mat = np.array(np.random.randint(10,100,15)).reshape(3,5)
mat

array([[60, 91, 77, 47, 57],
       [69, 32, 97, 66, 84],
       [16, 17, 91, 16, 58]])

In [226]:
mat[1:3, 1:4] # slicing based on Row and Column indexes

array([[32, 97, 66],
       [17, 91, 16]])

# Numpy Universal Functions

In [234]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
print(mat1)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print('\n',mat2)


[[5 5 1]
 [8 8 9]
 [7 3 9]]

 [[3 2 1]
 [9 5 9]
 [4 3 5]]


In [236]:
mat1*mat2 #This will NOT do matrix multiplication. It is just multiplying each number of mat1 to its correspoding number in mat2 as pwr index location

array([[15, 10,  1],
       [72, 40, 81],
       [28,  9, 45]])

In [238]:
mat1@mat2 #This is the Actual Matrix Multiplication

array([[ 64,  38,  55],
       [132,  83, 125],
       [ 84,  56,  79]])

In [241]:
np.log(mat1) #Logarithmic values

array([[1.60943791, 1.60943791, 0.        ],
       [2.07944154, 2.07944154, 2.19722458],
       [1.94591015, 1.09861229, 2.19722458]])

In [242]:
np.exp(mat1) #Exponential values

array([[1.48413159e+02, 1.48413159e+02, 2.71828183e+00],
       [2.98095799e+03, 2.98095799e+03, 8.10308393e+03],
       [1.09663316e+03, 2.00855369e+01, 8.10308393e+03]])